<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>
    <Import Project="$(SolutionDir)/build/code.quality.props"/>
    <ItemGroup>
        <PackageReference Include="BCrypt.Net-Next" Version="4.2.0"/>
        <PackageReference Include="MailKit" Version="4.17.0"/>
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12"/>
        <PackageReference Include="StackExchange.Redis" Version="2.7.27"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="../AiAdmin.Infrastructure/Data/menu-seed.json" Link="Data/menu-seed.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../AiAdmin.Core/AiAdmin.Core.csproj"/>
        <ProjectReference Include="../AiAdmin.Infrastructure/AiAdmin.Infrastructure.csproj"/>
    </ItemGroup>
</Project>